### ISSUE TITLE
Images from img.waffleimages.com cannot be downloaded

### ISSUE THREAD

**Issue by fletchowns** [fletchowns/awfulutils#11]
img.waffleimages.com seems to be long gone, which is unfortunate as it had a huge amount of image uploads for Something Awful forums. We used to be able to find these images @ 46.59.2.17 but that no longer seems to be up either.

Don't have a good solution for this unless somebody has another copy of these pictures somewhere.

**Comment by debdrup** [comment]
I have [a userscript](https://paste.sh/42OTytQa#w8TZl12kyM8aPbxzsRTNhVuS) which I got from somewhere on SA, and it uses randomwaffle.gbs.fm/images/ for the archive that's available there - it doesn't have _ALL_ the images, but some of them at least.

**Comment by fletchowns** [comment]
@debdrup I've pushed some changes to use this mirror. Thanks for letting me know about the mirror! Let me know how it goes with these latest changes. There are messages logged to the console when a waffleimages URL is detected and successfully translated to the backup mirror URL
